name: Publish

on:
  push:
    branches:
      - main
    schedule:
      - cron: '0 19 * * *' # Daily at 19:00

jobs:
  publish:
    name: Publish Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: netapp/ez-rancher/terraform-rancher
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: Dockerfile
          tags: "latest,${{ env.RELEASE_VERSION }}"
